Repository leolost2605/SBAid, pull requests merged in 2025-08, with the labels that each got.

#201 speed up database
  sbaid/model/database/global_database.py
  sbaid/model/database/global_sqlite.py
  sbaid/model/results/result_manager.py
  scripts/huge_interval.json
  scripts/test_dummy.json
  scripts/varied_dummy.json
  tests/model/database/test_global_sqlite.py
Labels: performance

#202 parameter config export
  sbaid/model/algorithm_configuration/csv_parameter_exporter.py
  sbaid/model/algorithm_configuration/csv_parameter_parser.py
  sbaid/model/algorithm_configuration/exporter_factory.py
  sbaid/model/algorithm_configuration/parameter_configuration.py
  sbaid/model/algorithm_configuration/parameter_export_format.py
  sbaid/model/algorithm_configuration/parameter_exporter.py
  sbaid/view_model/network/network.py
  tests/model/algorithm_configuration/mock_parameter_configuration.py
  tests/model/algorithm_configuration/param-export.csv
  tests/model/algorithm_configuration/test_algorithm_configuration.py
  tests/model/algorithm_configuration/test_csv_param_parser.py
  tests/model/algorithm_configuration/test_parameter_export.py
  tests/model/algorithm_configuration/valid_parameter_config.csv
Labels: nicht-bug

#273 Add the logo to the welcome page
  sbaid/view/start/welcome_page.py
Labels: cleanup
